### ISSUE TITLE
[Feature] should check if executed by user ardana?

### ISSUE THREAD

**Issue by SweBarre** [thorebahr/clim#2]
I was thinking if it makes sense to create a simple check if the script is executed as user ardnana?
Most of the paths are referenced with the ~/<path>/<to>/<folder> so it should fail if it's executed as root for example, but this should never be executed as any other user than ardana.
correct me if I'm wrong.
I would be more than happy to implement it, but wanted to make sure it made sense to do so.

**Comment by thorebahr** [comment]
yes - it makes sense, but I was doing this on a different way: the clim script itself is owned by the user ardana and has the attribute 700 - so only the ardana user is able to start it. Does this fit ?

**Comment by SweBarre** [comment]
that's one way to do it.
But it's not applied when others (read me) downloads the script and uses it. I'll create a pull request later.. cheers
